development:
  adapter: postgresql
  database: TuneCoreAlbumIndex_development
  pool: 25
  timeout: 5000
test: &test
  adapter: postgresql
  database: TuneCoreAlbumIndex_test
  pool: 25
  timeout: 5000

production:
  adapter: postgresql
  database: TuneCoreAlbumIndex_production
  pool: 25
  timeout: 5000
